openapi: 3.0.0
info:
  title: Trendloom API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.
servers:
  - url: 127.0.0.1
    description: Optional server description, e.g. Main (local) server